version: '3'
services:

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana:/var/lib/grafana

  influxdb:
    image: influxdb:1.7
    ports:
      - "8086:8086" # http api
    #  - "8089:8089" # udp api
    env_file:
      - ./influxdb/.influxdb.env
    volumes:
      - influxdb:/var/lib/influxdb

  particle:
    build:
      context: ./particle
    environment:
      - PARTICLE_USERNAME=${PARTICLE_USERNAME}
      - PARTICLE_PASSWORD=${PARTICLE_PASSWORD}
    volumes:
      - ./particle:/app

volumes:
  influxdb:
  grafana:
