version: '3'
services:

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.7
    ports:
      - "8086:8086" # http api
    #  - "8089:8089" # udp api
    env_file:
      - ./influxdb/.influxdb.env
    volumes:
      - influxdb:/var/lib/influxdb

  particle:
    build:
      context: ./particle
    environment:
      - PARTICLE_USERNAME=${PARTICLE_USERNAME}
      - PARTICLE_PASSWORD=${PARTICLE_PASSWORD}
    volumes:
      - ./particle:/app
    depends_on:
      - influxdb

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config

  mqtt:
    build:
      context: ./mqtt
    volumes:
      - ./mqtt:/app
    depends_on:
      - influxdb
      - mosquitto

  tempest:
    build:
      context: ./tempest
    environment:
      - WF_API_KEY=a8f5dbda-af0a-4b57-99b9-f10baa88f27b
      - DEVICE_ID=62760
    volumes:
      - ./tempest:/app
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb:
  grafana:
  mosquitto:
