version: '3'
services:

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influxdb
    restart: unless-stopped

  influxdb:
    image: influxdb:1.7
    ports:
      - "8086:8086" # http api
    #  - "8089:8089" # udp api
    env_file:
      - ./influxdb/.influxdb.env
    volumes:
      - influxdb:/var/lib/influxdb
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped

  ##
  # NodeJs
  ##

  aqi:
    image: node:14-alpine
    working_dir: /app
    command: npm start
    environment:
      - PURPLE_AIR_SENSOR_INDEX=${PURPLE_AIR_SENSOR_INDEX}
      - PURPLE_AIR_API_KEY=${PURPLE_AIR_API_KEY}
    volumes:
      - ./node/aqi:/app
    depends_on:
      - influxdb
    restart: unless-stopped

  mqtt:
    image: node:14-alpine
    working_dir: /app
    command: npm start
    volumes:
      - ./node/mqtt:/app
    depends_on:
      - influxdb
      - mosquitto
    restart: unless-stopped

  particle:
    image: node:14-alpine
    working_dir: /app
    command: npm start
    environment:
      - PARTICLE_USERNAME=${PARTICLE_USERNAME}
      - PARTICLE_PASSWORD=${PARTICLE_PASSWORD}
    volumes:
      - ./node/particle:/app
    depends_on:
      - influxdb
    restart: unless-stopped

  tempest:
    image: node:13-alpine
    working_dir: /app
    command: npm start
    ports:
      - "50222:50222/udp"
    environment:
      - UDP_PORT=50222
      - DEVICE_ID=62760
    volumes:
      - ./node/tempest:/app
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb:
  grafana:
  mosquitto:
